// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Adminuser struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type Codes struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Code        string    `json:"code"`
	Img         []byte    `json:"img"`
	Description string    `json:"description"`
	Performance string    `json:"performance"`
	Star        []int64   `json:"star"`
	Tags        []string  `json:"tags"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Access      int64     `json:"access"`
}

type Collection struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	CodeID int64 `json:"code_id"`
}

type Media struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Contents  string    `json:"contents"`
	Img       []byte    `json:"img"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Users struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Email       string    `json:"email"`
	Sex         string    `json:"sex"`
	DataOfBirth string    `json:"data_of_birth"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
