// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CountStar(ctx context.Context, codeID int64) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	CreateCode(ctx context.Context, arg CreateCodeParams) error
	CreateCollection(ctx context.Context, arg CreateCollectionParams) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) error
	CreateStar(ctx context.Context, arg CreateStarParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteCode(ctx context.Context, id int64) error
	DeleteCollection(ctx context.Context, id int64) error
	DeleteMedia(ctx context.Context, id int64) error
	DeleteStar(ctx context.Context, arg DeleteStarParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetAdminUser(ctx context.Context, arg GetAdminUserParams) (*Adminuser, error)
	GetAllCodes(ctx context.Context, arg GetAllCodesParams) ([]*Codes, error)
	GetAllCodesByKeyword(ctx context.Context, arg GetAllCodesByKeywordParams) ([]*Codes, error)
	GetAllCodesByTag(ctx context.Context, arg GetAllCodesByTagParams) ([]*Codes, error)
	GetAllCodesSortedAccess(ctx context.Context, arg GetAllCodesSortedAccessParams) ([]*Codes, error)
	GetAllCodesSortedStar(ctx context.Context, arg GetAllCodesSortedStarParams) ([]*Codes, error)
	GetCode(ctx context.Context, id int64) (*Codes, error)
	GetCollection(ctx context.Context, id int64) (*Codes, error)
	GetMedia(ctx context.Context, id int64) (*Media, error)
	GetUser(ctx context.Context, username string) (int64, error)
	ListCollections(ctx context.Context, arg ListCollectionsParams) ([]*ListCollectionsRow, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]*Media, error)
	LoginUser(ctx context.Context, arg LoginUserParams) (*Users, error)
	UpdateAccess(ctx context.Context, arg UpdateAccessParams) error
	UpdateCode(ctx context.Context, arg UpdateCodeParams) error
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) error
	UpdateStar(ctx context.Context, arg UpdateStarParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
