name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "building... $NAME"
        env:
          NAME: go
